# Cisco "ASA" app configuration for lograptor

[main]
description = Cisco ASA Security Appliance
tags = %ASA-
files = ${logdir}/${host}/%Y/%m/messages-%Y%m%d.log*
enabled = yes
priority = 10

[rules]
FRAG_POLICY = : Group = .+, Username = %{USER:user}, IP = %{IPORHOST:client}
               , IKE could not recognize the version of the client!\s{2}IPSec\s
               Fragmentation Policy will be ignored for this connection!
DENY_INBOUNT = : Deny inbound %{DATA:protocol} from %{IPORHOST:client1}/\d+\s
                to %{IPORHOST:client2}/\d+ on interface
LOGIN_FAILED = : Attempted console login failed user '%{USER:user}'\sdid NOT have appropriate Admin Rights.
EXEC_COMMAND = : User '%{USER:user}' executed the '%{DATA:command}' command
EXEC_CLIENT = : User '%{USER:user}', running 'CLI' from IP\s
              %{GREEDYDATA:client}, executed '%{DATA:command}'
EXEC_CLIENT2 = : Built outbound UDP connection \d+ for inside:
              %{IPORHOST:client1}/\d+ (%{IPORHOST:client1}/\d+) to\s
              %{DATA:interface}:%{IPORHOST:client3}/\d+ (%{IPORHOST:client4}/42115)
CLIENT_CONNECT = : connect from %{IPORHOST:client}
MAIL_RECEIVED = : %{ALNUM:thread}: from=<%{EMAIL:from}>, size=%{POSINT:size:int}, nrcpt=%{POSINT:mult:int}
# MAIL_SENT = : %{ALNUM:thread}: to=<%{EMAIL:rcpt}>,(\s(\S+),){4,5}\sstatus=sent

[totals]
subreport = mail
title = General Traffic Report
color = blue
function = total
MAIL_RECEIVED = (*, "Total Messages Processed")
