# "Barracuda Spam and Virus Firewall" app(liance) configuration for lograptor

[main]
description = Barracuda Spam and Virus Firewall appliance
tags = scan, outbound/smtp, inbound/pass1
files = ${logdir}/${host}/%Y/%m/maillog-%Y%m%d.log*
enabled = yes
priority = 10

[rules]
MAIL_SCAN = ^(scan|inbound/pass1)(\[%{POSINT:pid}\])?: %{IPORHOST:client} %{NCNAME:thread}\s
    \d+ \d+ SCAN \- %{EMAIL:from} %{EMAIL:rcpt} \S+ %{POSINT:action} %{POSINT:reason>}
MAIL_SEND = ^outbound/smtp(\[%{POSINT:pid}\])?: 127\.0\.0\.1 %{NCNAME:thread}\s
    0 0 SEND \S+ %{POSINT:action>}
MAIL_RCVD = ^inbound/pass1(\[%{POSINT:pid}\])?: %{IPORHOST:client}\[[0-9\.]+\] %{NCNAME:thread}\s
    \d+ \d+ RCVD %{EMAIL:from} %{EMAIL:rcpt} %{POSINT:action} %{POSINT:reason>}

[totals]
subreport = mail
title = [BSVF] General anti-SPAM Report
color = blue
function = total

MAIL_SCAN = (*,"Total Messages Scanned")
MAIL_SCAN1 = (action=="0","Allowed Messages")
MAIL_SCAN2 = (action=="2","Blocked Messages")
MAIL_SCAN3 = (action=="1","Aborted Messages")
MAIL_SCAN4 = (action=="4","Tagged Messages")
MAIL_SCAN5 = (action=="5","Deferred Messages at Scan level")
MAIL_SEND = (action=="3","Deferred Messages at Send level")

[top5_clients]
subreport = mail
title = [BSVF] Top 5 connecting hosts
color = blue
function = top(5,"Client host")

MAIL_SCAN1 = (*,client)

[top10_senders]
subreport = mail
title = [BSVF] Top 10 senders
color = blue
function = top(10,"Sender")
MAIL_SCAN1 = (*,from)

[top10_recipients]
subreport = mail
title = [BSVF] Top 10 recipients
color = blue
function = top(10,"Recipient")

MAIL_SCAN1 = (*,rcpt)

#[user_messages]
#enabled = False
#subreport = mail
#title = [BSVF] Messages sent by user
#function = table("Sender Address","Service","SMTP server used")
#MAIL_RECEIVED = (*,from,"postfix",hostname)
