# "crond" app configuration for lograptor

[main]
description = Cron Daemon
tags = crond, CROND, anacron, run-parts
files = ${logdir}/cron*, ${logdir}/${host}/%Y/%m/cron-%Y%m%d.log*
enabled = yes
priority = 9

[rules]
CRON_COMMAND = : \(%{NOTPAREN:user}\) CMD \(%{NOTPAREN:command}\)


# Subreport rules
[command_table]
subreport = command
title = Cron Commands 
function = table("Hostname","User","Commands")
CRON_COMMAND = (*,host,user,command)
