# "sshd" app configuration for lograptor

[main]
description = SSH daemon
tags = sshd
files = ${logdir}/secure*, ${logdir}/sshd*, ${logdir}/${host}/%Y/%m/secure-%Y%m%d.log*
enabled = yes
priority = 0

[rules]
User_Logins_PK = \[(?P<thread>\d+)\]: Accepted publickey for %{USER} from %{CLIENT}
User_Logins_PW = \[(?P<thread>\d+)\]: Accepted password for %{USER} from %{CLIENT}
User_Failures_PK = \[(?P<thread>\d+)\]: Failed publickey for %{USER} from %{CLIENT}
User_Failures_PW = \[(?P<thread>\d+)\]: Failed password for %{USER} from %{CLIENT}
Invalid_User_Fail = \[(?P<thread>\d+)\]: Failed password for invalid user %{USER}\s
                    from %{CLIENT}
Connection_Open = \[(?P<thread>\d+)\]: Connection from %{CLIENT} port (?P<port>\d+)
Connection_Closing = \[(?P<thread>\d+)\]: Closing connection to %{CLIENT}
Connection_Closed = \[(?P<thread>\d+)\]: Connection closed by %{CLIENT}
Session_Open = \[(?P<thread>\d+)\]: pam_unix\(.+\): session opened for user %{USER}\s
               by \(uid\=(?P<uid>${uid})\)
Session_Close = \[(?P<thread>\d+)\]: pam_unix\(.+\): session closed for user %{USER}
Matching_Key = \[(?P<thread>\d+)\]: Found matching (?P<algorithm>[\w\d-]+) key:\s
               (?P<key>(?:[0-9a-f]{2}:)+[0-9a-f]{2})
Postponed_Key = \[(?P<thread>\d+)\]: Postponed publickey for %{USER} from\s
                %{CLIENT} port (?P<port>\d+) ssh2
Client_Disconnect = \[(?P<thread>\d+)\]: Received disconnect from %{CLIENT}: (?P<reason>.+)
Connection_Timed_Out = \[(?P<thread>\d+)\]: Read error from remote host %{CLIENT}
                       : Connection timed out
Auth_Failures = \[(?P<thread>\d+)\]: (pam_unix\(.+\):|PAM \d+ more) authentication failure(s)?;\s
                (.+) rhost=%{CLIENT}(\s+)user=%{USER}
Set_Value = \[(?P<thread>\d+)\]: Set (?P<object>.+) to (?P<value>\d+)
Transferred = \[(?P<thread>\d+)\]: Transferred: sent (?P<sent>\d.+), received (?P<received>\d+)
User_PID = \[(?P<thread>\d+)\]: User child is on pid %{PID}
SFTP_Request = \[(?P<thread>\d+)\]: subsystem request for sftp
Disconnecting = \[(?P<thread>\d+)\]: Disconnecting: (?P<reason>.+)
Reverse_Fail = \[(?P<thread>\d+)\]: reverse mapping checking getaddrinfo for %{CLIENT} failed
LDAP_Reconnect = \[(?P<thread>\d+)\]: nss_ldap: reconnected to LDAP server
PAM_LDAP_Error = \[(?P<thread>\d+)\]: pam_ldap: error trying to bind as user "(?P<user>.+)"
Invalid_User = \[(?P<thread>\d+)\]: Invalid user %{USER} from %{CLIENT}
Auth_Invalid_User = \[(?P<thread>\d+)\]: input_userauth_request: invalid user %{USER}
PAM_Error = \[(?P<thread>\d+)\]: pam_succeed_if\(.+\): error retrieving information\s
            about user %{USER}
Missing_ID_String = \[(?P<thread>\d+)\]: Did not receive identification string from %{CLIENT}
Unknown_Host = \[(?P<thread>\d+)\]: error: connect_to %{USER}@%{CLIENT}: unknown host

##
# Report data items
#
[root_failures]
subreport = login
title = ROOT FAILURES
color = red
function = table("Hostname","Service","Client")
User_Failures_PK = (user=="\broot\b",host,"sshd(pk)",client)
User_Failures_PW = (user=="\broot\b",host,"sshd(pw)",client)

[root_logins]
subreport = login
title = ROOT Logins
color = blue
function = table("Hostname","Service","Client")
User_Logins_PK = (user=="\broot\b",host,"sshd(pk)",client)
User_Logins_PW = (user=="\broot\b",host,"sshd(pw)",client)

[user_failures]
subreport = login
title = User Failures
color = red
function = table("Username","Service","Server::client")
User_Failures_PK = (user!="\broot\b",user,"sshd(pk)",host,client)
User_Failures_PW = (user!="\broot\b",user,"sshd(pw)",host,client)

[user_logins]
subreport = login
title = User Logins
color = blue
function = table("Username","Service","Server::client")
User_Logins_PK = (user!="\broot\b",user,"sshd(pk)",host,client)
User_Logins_PW = (user!="\broot\b",user,"sshd(pw)",host,client)
