# "sudo" app configuration for lograptor

[main]
description = SUDO authorizations
tags = sudo
files = ${logdir}/secure*, ${logdir}/${host}/%Y/%m/secure-%Y%m%d.log*
enabled = yes
priority = 0

[rules]
# USER_LOGINS_PK = \[%{POSINT:thread}\]: Accepted publickey for %{USERNAME:user} from %{IPORHOST:client}
# USER_LOGINS_PW = \[%{POSINT:thread}\]: Accepted password for %{USERNAME:user} from %{IPORHOST:client}
USER_FAILURES_PK = \[%{POSINT:thread}\]: Failed publickey for %{USERNAME:user} from %{IPORHOST:client}
USER_FAILURES_PW = \[%{POSINT:thread}\]: Failed password for %{USERNAME:user} from %{IPORHOST:client}
SESSION_OPENED = : pam_unix(sudo:session): session opened for user %{USERNAME:user}(:by (uid=%{NONNEGINT:uid}\))?
SESSION_CLOSED = : pam_unix(sshd:session): session closed for user %{USERNAME:user}

#
# Report data items
#
[user_failures]
subreport = login
title = User Failures
color = red
function = table("Username","Service","Server::client")
USER_FAILURES_PK = (user!="\broot\b",user,"sudo",host,client)
USER_FAILURES_PW = (user!="\broot\b",user,"sshd",host,client)

[user_logins]
subreport = login
title = User Logins
color = blue
function = table("Username","Service","Server::client")
USER_LOGINS_PK = (user!="\broot\b",user,"sshd(pk)",host,client)
USER_LOGINS_PW = (user!="\broot\b",user,"sshd(pw)",host,client)
